
CREATE TABLE IF NOT EXISTS Sessions (
    ID INTEGER PRIMARY KEY, 
    timeStarted INTEGER DEFAULT CURRENT_TIMESTAMP );
CREATE TEMP TABLE CurrentSession (
    ID INTEGER, 
    FOREIGN KEY( ID ) REFERENCES Sessions(ID) );
CREATE TEMP TRIGGER storeCurrentSess 
AFTER INSERT ON Sessions 
FOR EACH ROW BEGIN 
    INSERT INTO CurrentSession (ID) VALUES (new.ID); 
END ;
INSERT INTO Sessions DEFAULT VALUES;
